### PR TITLE
Improve pipeline a6 as an example for a general approach change

### PR DESCRIPTION
**Pull request by sabinem**
This PR is a proposal by example of the dataset A6 to extend the pipelines and to also derive the queries for the tables in a more automatic way. 

### The basic idea: 

- output a sample of the table of about 40 rows with human readable spatial units as sample, that can be feed into chat gpt
- make a prompt for chatgpt to understand the task
- save the queries of chatgpt's answer
- test them with sqllite and finetune if needed

### ChatGPT not automated yet

- the output from ChatGPT was received manually since so far the goal was to avoid extra cost and it's just a onetime thing

### The actual changes: 

1. the script `A6.R` has been moved to a directory `pipelines/A6/A6.R` in order to provide space for additional elements that will be added to the pipeline.
2. SQLLite support has been set up for the package and `.gitignore` has been adapted to make sure that the database does not go into version control.
3. The pipeline has now functions that need to be run once in order to be picked up by R, since I felt it was nicer to directly have the actual flow in the first part of the file `A6.R`
4. There is a step now to print a sample of 40 random rows to a csv file as chatgpt input
5. The prompt used for chatgpt has been added as well
6. The output of chatgpt has been added into a query file
7. The last steps add the table into an sqllite instance and runs the queries for a test: the output can be checked: also it can be checked whether the questions make sense.

### Further suggestions

- Some of these functions can be generalized and added to the package if the example finds approval
- Chatgpt could be called per API as alternative

### CODE REVIEW

**Comment by cmdoret** [comment]
Nice idea! Here are a few points:

* Automating it will indeed require an API key
* Some of our tables have foreign keys (spatial units) from another table this means we will likely need to either:
  + Provide the sqlschema with both tables
  + Provide a sample of both tables
* R doesn't yet have much tooling (afaik) to interact with chatgpt. For example, the Python/javascript package langchain has a pre-built [SQL chain](https://python.langchain.com/docs/modules/chains/popular/sqlite) which does exactly that.
* Parsing the output of the model into a structured file takes a bit of effort (prompt tuning + post processing), this is already implemented in langchain.

I have the impression it may be easier to implement it separately from this repository.

**Comment by philbosch** [comment]
> I have the impression it may be easier to implement it separately from this repository. For example, we could have a python script which connects directly to the [postgres] db to generate the queries for each table.

👍  for this proposal! To keep it simpler we could also connect to the SQLite db which we create with the sample dataframe. Maybe this is in fact what you meant :D 
Connecting to the postgres db would again mean to supply credentials and only works for whitelisted IPs.

**Comment by cmdoret** [comment]
We just had a chat with Sabine, here's a way we could do it without too much effort:

* Keep a single repository
* One function to generate a prompt from a dataset
* The prompt contains the dataset name, table head, and some common context
* We just run the script, copy the prompt and paste it into chatgpt, it will output question/query pairs and we can save them

Least effort, free and code should be minimal (common across datasets). What do you think @philbosch ?

**Comment by sabinem** [comment]
Will not be implemented in that way, instead #33 will be used: test data will be created manually.

**Pull request closed without merging**
